//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('EmissionSources')
export class EmissionSourcesEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  sourceType: string;

  @Column('real', { nullable: true })
  quantityUsed: number;

  @Column('real', { nullable: true })
  emissionFactors: number;

  @Column('real', { nullable: true })
  totalEmissions: number;
}
