//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Goals')
export class GoalsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  name: string;

  @Column('text', { nullable: true })
  description: string;

  @Column('date', { nullable: true })
  targetDate: Date;

  @Column('integer', { nullable: true })
  relatedDepartment: number;

  @Column('text', { nullable: true })
  status: string;
}
