//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Users')
export class UsersEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  userName: string;

  @Column('integer', { nullable: true })
  department: number;

  @Column('text', { nullable: true })
  password: string;

  @Column('text', { nullable: true })
  email: string;
}
